//
// ArchiveAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class ArchiveAPI {
    /**
     Get Archive
     
     - parameter url: (query) Archive 
     - parameter page: (query) Paging 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getFootballArchive(url: String, page: Int, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: Archive?, _ error: Error?) -> Void)) {
        getFootballArchiveWithRequestBuilder(url: url, page: page).execute(apiResponseQueue) { result -> Void in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get Archive
     - GET /api/
     - parameter url: (query) Archive 
     - parameter page: (query) Paging 
     - returns: RequestBuilder<Archive> 
     */
    open class func getFootballArchiveWithRequestBuilder(url: String, page: Int) -> RequestBuilder<Archive> {
        let path = "/api/"
        let URLString = OpenAPIClientAPI.basePath + path
        let parameters: [String: Any]? = nil

        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
            "url": url.encodeToJSON(),
            "page": page.encodeToJSON(),
        ])

        let nillableHeaders: [String: Any?] = [
            :
        ]

        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<Archive>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, headers: headerParameters)
    }

}
