//
// Country.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Country: Codable, Identifiable {

    public var id: Int?
    public var name: String?
    public var flag: String?
    public var leagues: [Leagues]?

    public init(id: Int? = nil, name: String? = nil, flag: String? = nil, leagues: [Leagues]? = nil) {
        self.id = id
        self.name = name
        self.flag = flag
        self.leagues = leagues
    }

}
