//
// Football.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Football: Codable {

    public var countries: [Country]?

    public init(countries: [Country]? = nil) {
        self.countries = countries
    }

}
