//
// Leagues.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Leagues: Codable {

    public var id: Int?
    public var name: String?
    public var icon: String?
    public var seasons: [Seasons]?

    public init(id: Int? = nil, name: String? = nil, icon: String? = nil, seasons: [Seasons]? = nil) {
        self.id = id
        self.name = name
        self.icon = icon
        self.seasons = seasons
    }

}
