//
// Seasons.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Seasons: Codable {

    public var id: Int?
    public var season: String?
    public var pageCount: Int?
    public var archive: String?

    public init(id: Int? = nil, season: String? = nil, pageCount: Int? = nil, archive: String? = nil) {
        self.id = id
        self.season = season
        self.pageCount = pageCount
        self.archive = archive
    }

}
